
version: '3.2'
services:
  dockerized:
    # to enable caching, uncomment and set this:
    # image: <IMAGE_IDENTIFIER>
    build:
      context: .
      dockerfile: Dockerfile.dockerized
      # to enable caching, uncomment and set this:
      # cache_from:
      #   - <IMAGE_IDENTIFIER>
    entrypoint:
      - sh
      - '-c'
    environment:
      - CHAOSSEARCH_URL
      - CHAOSSEARCH_ACCESS_KEY_ID
      - CHAOSSEARCH_SECRET_ACCESS_KEY
    volumes:
      - gopath-cache:/go
      - terraform-dir:/root/.terraform.d

volumes:
  gopath-cache: {}
  terraform-dir: {}

